services:
  postgres:
    container_name: gomall-pg
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gomall
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gomall-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d gomall" ]
      interval: 10s
      timeout: 5s
      retries: 5





volumes:
  postgres_data:

networks:
  gomall-network:
    driver: bridge