services:
  postgres:
    container_name: gomall-pg
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gomall
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gomall-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d gomall" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: gomall-redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gomall-network
    command: redis-server --appendonly yes --requirepass secret
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  redis_data:

networks:
  gomall-network:
    driver: bridge