server:
  port: ":8080"
  mode: "debug" # debug, release

database:
  host: "localhost"
  port: 5433
  user: "root"
  password: "secret"
  dbname: "gomall"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

jwt:
  secret: "12345678901234567890123456789012" # Must be at least 32 characters
  access_token_duration: 15m
  refresh_token_duration: 24h

email:
  sender_name: "GoMall"
  sender_email: "bybhwric@gmail.com"  # 替换为你的 Gmail
  sender_password: "ymcy sfdp wobk zcdi"   # Gmail 应用专用密码，不是登录密码